# Problem 288: An enormous factorial
# http://projecteuler.net/problem=288

# 
# For any prime p the number N(p,q) is defined by
# N(p,q) = ∑n=0 to q Tn*p^n with Tn generated by the following random number generator:
# 
# S0 = 290797
# Sn+1 = Sn^2 mod 50515093
# Tn = Sn mod p
# 
# 
# Let Nfac(p,q) be the factorial of N(p,q).
# Let NF(p,q) be the number of factors p in Nfac(p,q).
# 
# 
# You are given that NF(3,10000) mod 3^20=624955285.
# 
# 
# Find NF(61,10^7) mod 61^10
# 
#     

